repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest revision
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

repos:
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3
    args: [--line-length=88]

- repo: https://github.com/pycqa/flake8
  rev: '3.9.2'  # or whatever the latest version is
  hooks:
  - id: flake8
    args: [--max-line-length=88, --extend-ignore=E203]
