version: '3.8'

services:
  chatgpt_service:
    build: ./top_secret/services/chatgpt_service
    network_mode: host
    env_file:
      - .env

  webpage_scraper_service:
    build: ./top_secret/services/webpage_scraper_service
    network_mode: host

  text_summarizer_service:
    build: ./top_secret/services/text_summarizer_service
    network_mode: host
    volumes:
      - /media/aiwaldoh/LLM/models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  logging_service:
    build: ./top_secret/services/logging_service
    network_mode: host
    volumes:
      - "/home/aiwaldoh/Development/python/projects/top-secret/logs:/app/logs"

  command_executor_service:
    build: ./top_secret/services/command_executor_service
    network_mode: host
    volumes:
      - "/home/aiwaldoh/Development/python/projects/top-secret/working_directory:/app/data"
      - ssh-keys:/root/.ssh # Mount the SSH keys volume to /root/.ssh

  api_gateway:
    build: ./top_secret/api_gateway
    network_mode: host
    env_file:
      - .env

  texttospeech_service:
    build: ./top_secret/services/texttospeech_service
    network_mode: host
    depends_on:
      - tts_service
    # Add any other configuration needed for this service

  tts_service:
    image: ghcr.io/coqui-ai/tts
    ports:
      - "5002:5002"
    entrypoint: python3 TTS/server/server.py
    command: --model_name tts_models/en/vctk/vits --use_cuda true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu" ]

volumes:
  ssh-keys: # Define the volume for SSH keys
